### PR TITLE
Dependency and i18n Updates

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Dependency changes 
- i18n Changes

### CODE REVIEW

**Comment by emclaug2** [comment]
I'm converting this to a draft since dev ci/cd tests are failing.

**Comment by joebochill** [comment]
@jeffvg maybe this is in your wheelhouse

**Comment by jeffvg** [comment]
> Can you look into what's going on with the cypress tests?

looking at this once PC starts up

**Comment by emclaug2** [comment]
Tests are now passing, this is ready for review.

**Review by joebochill — APPROVED** [review]

**Review by huayunh — APPROVED** [review]

**Pull request merged**
