### PR TITLE
Feature/overlay refactor

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
-  Use HeroBanner and Heroes in the complex bottom sheet example.

#### Screenshots:
image

### CODE REVIEW

**Comment by emclaug2** [comment]
The overline typography doesn't match against what we have in the angular design patterns.  Is this a theme change?

**Comment by emclaug2** [comment]
Left: React
Right: Angular

image

**Review by joebochill — COMMENTED** [review]
Can we delete the IconToggle file now?

**Comment by joebochill** [comment]
> The overline typography doesn't match against what we have in the angular design patterns. Is this a theme change?

Could be...where are the font weights/sizes coming from?

**Comment by emclaug2** [comment]
> > The overline typography doesn't match against what we have in the angular design patterns. Is this a theme change?
> 
> Could be...where are the font weights/sizes coming from?

The angular font weights are coming from the pxblue angular theme.

**Comment by joebochill** [comment]
> > > The overline typography doesn't match against what we have in the angular design patterns. Is this a theme change?
> > 
> > 
> > Could be...where are the font weights/sizes coming from?
> 
> The angular font weights are coming from the pxblue angular theme.

Angular is correct. We need to update this project to use @pxblue/react-themes@5.0.2 to get the latest typography tweaks from a few months ago (overline fontWeight 400 -> 600)

**Review by joebochill — APPROVED** [review]

**Comment by emclaug2** [comment]
> > > > The overline typography doesn't match against what we have in the angular design patterns. Is this a theme change?
> > > 
> > > 
> > > Could be...where are the font weights/sizes coming from?
> > 
> > 
> > The angular font weights are coming from the pxblue angular theme.
> 
> Angular is correct. We need to update this project to use @pxblue/react-themes@5.0.2 to get the latest typography tweaks from a few months ago (overline fontWeight 400 -> 600)

This did the trick 👍

**Pull request merged**
