### PR TITLE
Appbars - page wide search

### PR DESCRIPTION
**Pull request by daileytj**
Fixes PXBLUE-2424.

#### Changes proposed in this Pull Request:
- Add page wide search example

#### Screenshots:
Screen Shot 2021-09-20 at 2 08 04 PM
Screen Shot 2021-09-20 at 2 07 51 PM

### CODE REVIEW

**Comment by jeffvg** [comment]
something odd....when resized down to like 450x450 to force vertical scroll....but not always happening.


https://user-images.githubusercontent.com/37150565/134058314-0565513d-3e13-4c97-82ac-00c333d447fc.mov

**Comment by jeffvg** [comment]
image

**Comment by huayunh** [comment]
I can play around with the CSS tomorrow. I've seen the thing Jeff is discovering outside Tom's branch — might be worth logging a separate bug.

**Comment by jeffvg** [comment]
FireFox gives more info on error. Resize height down to 450 then scroll page down. Next adjust width down to 450 and the search field adjusts to mobile/tablet. Then scroll up or down.

image

**Comment by emclaug2** [comment]
Can you add a search icon here? 
image

**Comment by ektasawant** [comment]
Looks good 👍 . 
Few comments :
1. As per design use for mobile view use title `Page Search`  so that it will not go to second line.
2. Rename `Search` to `Search Assets...`
3. Do we need to hide close icon when input is not focus? i.e. show close icon when user starts typing or focus on input.

**Comment by daileytj** [comment]
> Looks good 👍 .
> Few comments :
> 
> 1. As per design use for mobile view use title `Page Search`  so that it will not go to second line.
> 2. Rename `Search` to `Search Assets...`
> 3. Do we need to hide close icon when input is not focus? i.e. show close icon when user starts typing or focus on input.

1. What do you mean by "so it will not go to second line"? Can you send a screenshot.
2. I can rename `Search` to `search assets...`, I just didn't think it made sense since we were searching fruit so I just left it as `Search`
3. The close icon isn't part of the input, so if I add the functionality to hide the close button when not focused the close button disappears before it's clicked so you can never actually clear the input if we do that. I ended up just showing the x when there is text in the input.

@huayunh could use your input on 2 and 3.

**Comment by mvbela** [comment]
1. The "Wide" in "Page Wide Search" is withdrawn if there are too many characters and they don't fit the appbar, with proper space for the icon buttons. In this case, use "Page Search" on mobile, and "Page-wide Search" in desktop
2. Let's rename "Assets" for "Items". "Search items" there
3. The close button should be visible every time the input field in focused, the user is typing or there's an input entered. Only not visible when no search is active.

**Review by emclaug2 — CHANGES_REQUESTED** [review]
Can you fix this search icon alignment? : 

image

Also whenever a user starts to search, the text that they typed in should appear as bolded in the search results list.  There's some code within the feature/global-search branch that adds this logic in; you could just copy/paste it or better yet import it once merged.

**Comment by emclaug2** [comment]
Whenever there's no results found, for consistency, just display "No results" instead of an EmptyState.

image

**Comment by emclaug2** [comment]
Also can you make it so the search bar on mobile is no longer sticky on scroll; it should just be an inline element.

**Comment by daileytj** [comment]
> Can you fix this search icon alignment? :
> 
> image
> 
> Also whenever a user starts to search, the text that they typed in should appear as bolded in the search results list. There's some code within the feature/global-search branch that adds this logic in; you could just copy/paste it or better yet import it once merged.

Took care of all the other stuff... but, what's wrong with the alignment here?

**Comment by huayunh** [comment]
You can use a dense variant of that text field, and hopefully, the label text would be gone. And you would not have to worry about alignments

**Comment by emclaug2** [comment]
@daileytj This is how it's looking for angular:

With Text:
image

No Search Text:
image

**Comment by daileytj** [comment]
Design File
Screen Shot 2021-09-22 at 1 49 12 PM

Current state of react input
Screen Shot 2021-09-22 at 1 49 46 PM

??

**Comment by daileytj** [comment]
Also, the small size variant doesn't change anything

**Comment by daileytj** [comment]
Looks like there are discrepancies in the placeholder colors too... 🙄

**Comment by emclaug2** [comment]
> Looks like there are discrepancies in the placeholder colors too... 🙄

Would this be considered a theme change?  Taking a look at the Input field w/ icon now.

**Comment by emclaug2** [comment]
Search input looking good now, must have been an outdated thing on my end.

**Comment by huayunh** [comment]
@mvbela, please do not use outdated components directly in your latest design.

image

**Comment by emclaug2** [comment]
@huayunh  @daileytj Is this the intended scroll behavior?  I thought this bar was supposed to just be an inline-element and scroll off the page.

sticky

**Comment by daileytj** [comment]
That's strange Evan... It was scrolling behind the main appbar previously... let me take a look.

**Comment by daileytj** [comment]
Should be good now. I'm using the mui appbar and by default they have a z-index of 1100. Just bumped up the z-index on the main appbar so everything flows beneath it. I could also make the z-index of the second appbar 0 instead if we feel that is a better approach.

**Comment by huayunh** [comment]
Did some fixes in https://github.com/pxblue/react-design-patterns/pull/94 
Looks cool with me otherwise

**Review by huayunh — APPROVED** [review]

**Comment by daileytj** [comment]
Thanks @huayunh!

@emclaug2 I think this is good to go, just needs your approval.

**Comment by emclaug2** [comment]
Scroll behavior is great!  One last thing:

Very strange blue appearing when transitioning from desktop to mobile: 
blue

**Comment by daileytj** [comment]
> Scroll behavior is great! One last thing:
> 
> Very strange blue appearing when transitioning from desktop to mobile:
> blue

@emclaug2 Ahh, I did notice that too. Not sure what it is, but I'll investigate. I'm starting to crave straight-up SASS/CSS in react lately.

**Review by emclaug2 — APPROVED** [review]

**Pull request merged**
