### PR TITLE
add cypress tests

### PR DESCRIPTION
**Pull request by jeffvg**
#### Changes proposed in this Pull Request:
- add tests for contextual-spinners, progress-bars, skeleton-loader and spinner-overlay
- update bottomsheet cypress test to run dismiss bottomsheet first
- 

#### To Test:
-

### CODE REVIEW

**Comment by emclaug2** [comment]
Hey @jeffvg how do you test these cypress tests locally?  I've ran `yarn && yarn cytest` but am hit with a bunch of failed tests.

**Comment by jeffvg** [comment]
> Hey @jeffvg how do you test these cypress tests locally? I've ran `yarn && yarn cytest` but am hit with a bunch of failed tests.

yarn cytest should work...after dev server starts you should see CY client running like this...
image

**Comment by jeffvg** [comment]
> > Hey @jeffvg how do you test these cypress tests locally? I've ran `yarn && yarn cytest` but am hit with a bunch of failed tests.
> 
> yarn cytest should work...after dev server starts you should see CY client running like this...
> image

or you can try
npx cypress open

**Comment by joebochill** [comment]
The tests all ran for me locally

**Review by joebochill — APPROVED** [review]

**Pull request merged**
