### PR TITLE
add body content

### PR DESCRIPTION
**Pull request by ektasawant**
Fixes [81](https://github.com/pxblue/react-design-patterns/issues/81) .

#### Changes proposed in this Pull Request:
- Show dummy content

#### To Test:
-

### CODE REVIEW

**Review by emclaug2 — COMMENTED** [review]
I have an ultrawide monitor so this example actually gives me some issues; I can't scroll down.

Here's what I see: 
image

What do you think about making the body content have a max width so it looks something like this?
image


@huayunh thoughts?

**Comment by huayunh** [comment]
fine w me

**Review by jeffvg — APPROVED** [review]
900 width is ok could be smaller area

**Comment by emclaug2** [comment]
This works great on wider monitors.

**Review by emclaug2 — APPROVED** [review]

**Pull request merged**
