### PR TITLE
Feature/pxblue 2543 action list inline

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes # PXBLUE-2543

#### Changes proposed in this Pull Request:
- Added list with inline actions
- Added mobile view styles
- Updated UI test cases

#### Screenshots:
**Desktop**
Screenshot 2021-11-12 at 5 42 55 PM

**Mobile**
Screenshot 2021-11-12 at 5 47 43 PM

#### To Test:
- http://localhost:3000/inline-actions
- Hover on any of the items in Desktop view to see actions
- Click on any of the item's morevert icon in Mobile view to see actions

### CODE REVIEW

**Comment by ektasawant** [comment]
1. @mariana  Do we need to delete row when click on delete icon? Or it is just a placeholder ?

2. @bkarambe can you fix the position of select option in mobile view similar to other `In panel header` design pattern.
Screenshot 2021-11-15 at 10 01 36 AM

**Comment by bkarambe** [comment]
> 1. @mariana  Do we need to delete row when click on delete icon? Or it is just a placeholder ?
> 2. @bkarambe can you fix the position of select option in mobile view similar to other `In panel header` design pattern.
> 
> Screenshot 2021-11-15 at 10 01 36 AM

Done.

**Comment by ektasawant** [comment]
After deleting all rows , it is showing blank screen.
Screenshot 2021-11-15 at 5 58 17 PM
@bkarambe, @mariana do we have any design for empty state ?

**Comment by mvbela** [comment]
Hi @bkarambe !

When all items are deleted, the screen should show:

Desktop: 
Captura de ecrã 2021-11-15, às 13 27 39

Mobile: 
Captura de ecrã 2021-11-15, às 13 27 49

**Comment by bkarambe** [comment]
> Hi @bkarambe !
> 
> When all items are deleted, the screen should show:
> 
> Desktop: Captura de ecrã 2021-11-15, às 13 27 39
> 
> Mobile: Captura de ecrã 2021-11-15, às 13 27 49

Done.

**Comment by mvbela** [comment]
Hi @bkarambe !

I'm not sure if it's wrong, but it feels off - can you double check if the shadow is correct? It should be 06dp
Captura de ecrã 2021-11-16, às 13 39 28

When I'm resizing the screen, the dropdown does not seem ok
Smaller sizes (mobile) - ok 
Captura de ecrã 2021-11-16, às 13 36 35

Mid sizes - doesn't have correct sizes
Captura de ecrã 2021-11-16, às 13 36 49


On hover, the actions should have a blue highlight background, which isn't happening

Captura de ecrã 2021-11-16, às 13 43 05

**Comment by bkarambe** [comment]
> Hi @bkarambe !
> 
> I'm not sure if it's wrong, but it feels off - can you double check if the shadow is correct? It should be 06dp Captura de ecrã 2021-11-16, às 13 39 28
> 
> When I'm resizing the screen, the dropdown does not seem ok Smaller sizes (mobile) - ok Captura de ecrã 2021-11-16, às 13 36 35
> 
> Mid sizes - doesn't have correct sizes Captura de ecrã 2021-11-16, às 13 36 49
> 
> On hover, the actions should have a blue highlight background, which isn't happening
> 
> Captura de ecrã 2021-11-16, às 13 43 05

Done. PR has been updated with the suggested changes.

**Comment by ektasawant** [comment]
Hi @bkarambe , please check below comments:

1. Divider is not taking full screen width for No result
Screenshot 2021-11-22 at 10 58 16 PM

2. When user clicks on reset data link it should show default listItems. Right now we have to refresh page to see list

3. `This behaviour is exclusive to desktop version.` text is missing.
Screenshot 2021-11-22 at 11 08 10 PM

**Review by ektasawant — APPROVED** [review]
Changes looks good.

**Comment by bkarambe** [comment]
@mvbela

**Comment by emclaug2** [comment]
If there's no comments on this mid-day I'll just merge it in.

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
