### PR TITLE
Firebase Deploy

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Firebase deploy test

### CODE REVIEW

**Review by jeffvg — APPROVED** [review]

**Review by huayunh — CHANGES_REQUESTED** [review]
Firebase is not set up properly for a single-page app. Right now if you go into any design patterns page and do a refresh, Firebase would return a 404.

**Comment by jeffvg** [comment]
> Firebase is not set up properly for a single-page app. Right now if you go into any design patterns page and do a refresh, Firebase would return a 404.

Does it give an error. I did not want to over right the index and thats why its setup this way

**Comment by jeffvg** [comment]
> 

@huayunh give it a try now, added the entry for SPA

**Review by huayunh — APPROVED** [review]
Works now

**Pull request merged**
