### PR TITLE
Feature/form validation match ng

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Add check indicator to first 3 input fields.
- Move new password criteria below new password field; add checkmark to each requirement.
- Add password visibility field to password input fields. 

#### Screenshots:

Angular:
image

React:
image

### CODE REVIEW

**Comment by emclaug2** [comment]
These patterns look very different, should I update React to match Angular (or vise versa)? @jeffvg @huayunh @joebochill

**Comment by joebochill** [comment]
> The overall layout of these patterns look very different, should I update React to match Angular (or vise versa)? @jeffvg @huayunh @joebochill

I prefer the look of the Angular

**Comment by jeffvg** [comment]
> > The overall layout of these patterns look very different, should I update React to match Angular (or vise versa)? @jeffvg @huayunh @joebochill
> 
> I prefer the look of the Angular

I guess the React example is full screen and Angular is set in a 600px wide div for entire form.

**Comment by emclaug2** [comment]
> > The overall layout of these patterns look very different, should I update React to match Angular (or vise versa)? @jeffvg @huayunh @joebochill
> 
> I prefer the look of the Angular

I agree; I'll update React to match angular's layout as close as possible.

**Comment by huayunh** [comment]
I like Angular's page layout

I don't think that checkmark within the input field thing is encouraged anywhere in our designs (asked Ian before and he said we didn't use it in our current designs). Maybe @Horchen154 can react to this.

**Comment by emclaug2** [comment]
Latest update:

I've matched the general layout of the React patterns to match Angular.
I've also updated the typography to match & made sure the descriptions match.


The input fields still look very different from each other; is this a change that should happen as well? 
image

**Comment by jeffvg** [comment]
seems that the visibility on password fields are not triggerig

image

**Comment by jeffvg** [comment]
some strange behavior on input field and character limit field. If you enter text in the input field to produce the check mark then enter text in the character count field and back that text out and tab out, the input field above triggers error state.....

image

**Comment by emclaug2** [comment]
I forgot the enable password visibility!  This should be working now @jeffvg

**Comment by emclaug2** [comment]
Here's the new look: 

image

I think the React filled variant will need to have a theme change.

**Pull request merged**
