### PR TITLE
wait on server to use strict version update test

### PR DESCRIPTION
**Pull request by jeffvg**
#### Changes proposed in this Pull Request:
- cytest runs locally no issues, need to verify what CI does now
- wait on server was running on 1.11.14 and we want 1.11.1 for now
- update sortable test to include "ListItemAvator-root" with get action to focus test on entire row with handlebar

### CODE REVIEW

**Comment by joebochill** [comment]
I suggest commenting out the filters part of the config.yml temporarily so we can see if those tests pass in CI (without having to merge a bunch of PRs to try and debug the problem in the dev/master branches).

What changed in start-server-and-test from 1.11.1 and 1.11.14? These are only patch changes, so I wouldn't expect there to be any braking changes in there.

**Comment by jeffvg** [comment]
> I suggest commenting out the filters part of the config.yml temporarily so we can see if those tests pass in CI (without having to merge a bunch of PRs to try and debug the problem in the dev/master branches).
> 
> What changed in start-server-and-test from 1.11.1 and 1.11.14? These are only patch changes, so I wouldn't expect there to be any braking changes in there.

on CI we were getting this error - Error: server closed unexpectedly
    at ChildProcess.onClose (/home/circleci/react-design-patterns/node_modules/start-server-and-test/src/index.js

We seen this before where the server does start and then stops or the server is running but a status 200 doesn't trigger.
There is an open issue similar to this that I ran across and thought is was possible issue.
https://github.com/bahmutov/start-server-and-test/issues/283

**Comment by jeffvg** [comment]
> I suggest commenting out the filters part of the config.yml temporarily so we can see if those tests pass in CI (without having to merge a bunch of PRs to try and debug the problem in the dev/master branches).
> 
> What changed in start-server-and-test from 1.11.1 and 1.11.14? These are only patch changes, so I wouldn't expect there to be any braking changes in there.

doing this now

**Comment by jeffvg** [comment]
running with wait-on instead of start-server-and-test seems to be ok. We used this package before so we might need to keep this until react-scripts 3.4.X gets updated.

https://app.circleci.com/pipelines/github/pxblue/react-design-patterns/123/workflows/362f00ca-f66c-41ed-8a45-df428400bce4/jobs/149

**Review by joebochill — APPROVED** [review]

**Pull request merged**
