### PR TITLE
Go BLUI

### PR DESCRIPTION
**Pull request by emclaug2**
Go BLUI

### CODE REVIEW

**Comment by emclaug2** [comment]
If the cypress tests pass, I'll mark this as ready-for-review.

**Comment by emclaug2** [comment]
Before this makes it to master there's 1 cytest failing.

**Review by jeffvg — APPROVED** [review]

**Comment by daileytj** [comment]
The Eaton logo isn't showing. This is because the drawer footer image src is referencing an image that doesn't exist. The original logo was stored on Github.  A "pxblue" find and replace would break this since there is no brightlayer-ui org yet. Should probably just host this image in the assets folder...

Screen Shot 2021-12-06 at 3 01 15 PM

 Screen Shot 2021-12-06 at 2 59 52 PM

**Review by daileytj — APPROVED** [review]
Approving this, assuming the Eaton logo is set up the way it is for codesandbox and that it will start working as soon as we change the org name.

**Pull request merged**
